//
// Created by niko on 23.05.2021.
//

#ifndef REDIS_ASYNC_ERROR_HPP
#define REDIS_ASYNC_ERROR_HPP

#include <stdexcept>

namespace redis_async {
    namespace error {

        /**
         * @brief Base class for exceptions generated by the library
         */
        class rd_error : public std::runtime_error {
        public:
            explicit rd_error(const std::string &msg);
            explicit rd_error(const char *msg);
        };

        /**
         * @brief Connection with the database server failure.
         * Includes network and authentication failures.
         */
        class connection_error : public rd_error {
        public:
            explicit connection_error(const std::string &msg);
            explicit connection_error(const char *msg);
        };

        /**
         * @brief An error generated by the Redis server when executing a query.
         */
        class query_error : public rd_error {
        public:
            explicit query_error(const std::string &msg);
            explicit query_error(const char *msg);
        };

    } // namespace error
} // namespace redis_async

#endif // REDIS_ASYNC_ERROR_HPP
